### ISSUE TITLE
File size

### ISSUE THREAD

**Issue by MusculusMus** [alexvpickering/GEOfastq#1]
Hi, I tried the package to download fastq files. I checked the files and the size doesn't match the number in the progress, way more smaller than the expected size.

**trying URL 'ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR768/002/SRR7689142/SRR7689142_1.fastq.gz'
Content type 'unknown' length 3865995719 bytes (3686.9 MB)**

Shuai

**Comment by alexvpickering** [comment]
Did you bump the download timeout option (default is 60s)? Something like this:

```R
# bump download time for utils::download.file
options(timeout=1e6)
```

If that doesn't work, please post a reproducible example.

**Comment by MusculusMus** [comment]
Yes, I found your instructions somewhere else and it is working well now. Thanks. Can you close the post ?

shuai wang

________________________________
发件人: Alex Pickering ***@***.***>
发送时间: Saturday, October 1, 2022 9:15:04 AM
收件人: alexvpickering/GEOfastq ***@***.***>
抄送: Shuai Wang ***@***.***>; Author ***@***.***>
主题: Re: [alexvpickering/GEOfastq] File size (Issue #1)


Did you bump the download timeout option (default is 60s)? Something like this:

# bump download time for utils::download.file
options(timeout=1e6)

If that doesn't work, please post a reproducible example.

―
